Modify health check to allow more startup time
Increase wait time for Odoo to start and update health check.

diff --git a/.github/workflows/deploy-17.0.yml b/.github/workflows/deploy-17.0.yml
--- a/.github/workflows/deploy-17.0.yml
+++ b/.github/workflows/deploy-17.0.yml
@@ -60,5 +60,6 @@ jobs:
 
       - name: Health check
         run: |
-          sleep 10
-          curl -f http://${{ secrets.VM_HOST }}:8070/web/database/selector || (echo "Health check failed" && exit 1)
+          echo "Waiting for Odoo to start..."
+          sleep 30
+          curl -Isf http://${{ secrets.VM_HOST }}:8070/web/database/selector || (echo "Health check failed but container might still be starting" && exit 1)
